### ISSUE TITLE
Links to what else Github can be used for

### ISSUE THREAD

**Issue by eddiejaoude** [OpenSourceAtoZ/how-to-use-github#1]
eg.
- Travel diary
- Receipts
- Legal / Gov docs

**Comment by rapidexpert** [comment]
@eddiejaoude you can find the links in this article
http://readwrite.com/2013/11/08/seven-ways-to-use-github-that-arent-coding/

**Comment by eddiejaoude** [comment]
Thanks, I think that is the one Frederica sent me :smile:  ... great minds :+1:
